### ISSUE TITLE
SSLRead error with the Guzzle6HttpAdapter

### ISSUE THREAD

**Issue by mrbase** [egeloen/ivory-http-adapter#121]
When using the Guzzle6HttpAdapter as an adapter for Geocoder\Provider\GoogleMaps I get a HttpAdapterException: 

    cURL error 56: SSLRead() return error -9806 (see ....)

I'm on Homebrew so I had to set `['verify' => true]` on the Guzzle Client otherwise the error is:

    cURL error 51: SSL: certificate verification failed

Any ideas or thoughts on this ?

**Comment by mrbase** [comment]
Might add that It's only when I use apiKey for the provider:

```php
$x = new GoogleMaps(new Guzzle6HttpAdapter(new Client(['verify' => true])), null, null, true, '<api-key>');
```

**Comment by egeloen** [comment]
Hum, do you need to do the same for other guzzle adapters (for example guzzle 5)? The point is this library should ratiozalize the way sub http library works. I must admit there is not tests about SSL currenctly so, there is maybe something wrong about this behavior accross the different adapters...

**Comment by mrbase** [comment]
Yeah, I can reproduce the error with the Guzzle5HttpAdapter.

test.php
```php
<?php
require __DIR__.'/../vendor/autoload.php';

use GuzzleHttp\Client;
use Geocoder\Provider\GoogleMaps;
use Ivory\HttpAdapter\Guzzle5HttpAdapter;

$guzzle = new Client(['verify' => true]);
$geocoder = new GoogleMaps(new Guzzle5HttpAdapter($guzzle), null, null, true, '<google token>');
$coded = $geocoder->geocode('<some address>');
```
composer.json
```json
{
    "require": {
        "guzzlehttp/guzzle": "5.x",
        "willdurand/geocoder": "~3.1"
    }
}
```

**Comment by djaed** [comment]
Got same error trying to geocode with google maps with SSL and API-KEY. 

My problem was that on my MAC, PHP was compiled with cURL that uses Apple's Secure Transport , instead of supporting OpenSSL. To check try: 
```
php -i | grep "SSL Version"
```
once confirmed that I wasn't using OpenSSL and needed to reinstall cURL with OpenSSL and recompile PHP, i thought i might as well upgrade from 5.5 to 5.6 while at it. 

Doing following solved my problem ... Using homebrew:
```
rm ~/.pearrc
brew update
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/php
brew install curl --with-openssl
brew unlink php55
brew install php56 --with-apache --with-homebrew-curl --with-homebrew-libxslt --with-homebrew-openssl --with-tidy --without-snmp
```
Then set Apache's httpd.config to use new php56:
```
LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so
```
And also edit new php.ini, e.g. 
```
date.timezone = "Europe/London", etc. ...
```
And finally restart Apache:
```
sudo apachectl restart
```
Thats it. I can now geocode with SSL.

BTW, following links helped me with above: 

1. http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error
2. http://www.farces.com/wikis/naked-server/php/php-openssl/

**Comment by mrbase** [comment]
Ah, thanks - that also did it for me :)
