### ISSUE TITLE
What about PHP HTTP?

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#122]
Hey @egeloen,

I am trying to contact you for a while now, I am a bit sad I have to do it through this issue. I am doing it because you don't answer emails, tweets or any other form of communication I tried. As I can see you are not dead, since you develop this package.

Did something happen? Can we talk privately? The topic would of course be PHP HTTP. I have some feedback that other projects would rely on it once it gets stable. I made progress since May, mostly aligned with our plans, but there are some other changes as well which we haven't discussed.

I am not sure about your future plans related to the project, so it would be good if we could talk privately about it.

Cheers,
Mark

**Comment by sagikazarmark** [comment]
@egeloen ping :)

**Comment by egeloen** [comment]
Sorry for the lack of activity/response but I'm on a project which currently never ends and I'm totaly busy since months... Anyway, I'm still in favor of PHP HTTP but I have no time for it right now. I am currently switching on an other mission (in the next days) and it should stabilize my daily workload ,so, I should be available again for open source projects.

@sagikazarmark I will ping you on gitter for discussing when I have some time.

**Comment by dbu** [comment]
glad to hear this! i think PHP HTTP is a great chance for you to need to be less responsible for things, but we need to make a good transition from the ivory http adapter to not get people lost and confused.

**Comment by sagikazarmark** [comment]
@egeloen thanks for letting us know. There is absolutely no problem with that. Glad to hear the news.
