### ISSUE TITLE
Implement event driven logic as decorator

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#63]
Currently this logic is encapsulated into all adapters. Implementing it as a decorator would leave it transparent, but make it optional (currently it is not). Also would make the code cleaner. It would probably require some minor structural change in the code.

The point is that decoupling event handling from adapters would make this a plain adapter package, where event layer is an extra on top of it.

What do you think?

**Comment by remdan** [comment]
I support the proposal...particularly the last sentence, I prefer a plain adapter package too.

**Comment by dominikzogg** [comment]
+1

**Comment by sagikazarmark** [comment]
@egeloen ping

Also, this would make #64 invalid

**Comment by egeloen** [comment]
Sorry for the delay, I'm a little bit busy currently. Regarding the proposition, I have mostly making it mandatory in order to solve common use cases for all adapters in the exact same way. For example, it is difficult to handle the redirect for all adapters with the same behavior for all of them.

Anyway, If everyone agrees to move it as decorator, I'm :+1: too.

**Comment by sagikazarmark** [comment]
@egeloen IMO that's why PSR7 will be an awesome thing when it gets ready. You will be able to do things the same way.

Anyway, this is something that bugs me for a long time now. This is why I originally started my own adapter package, but I ended up here when you removed events being mandatory. So I am so much :+1: for having it as a decorator.

**Comment by sagikazarmark** [comment]
Will this be part of any near release?
