### ISSUE TITLE
Decorator logic

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#65]
I checked the Stopwatch adapter and I realized that it is not a real decorator. It extends the template class which does not call the underlying `get`, `post`, etc, but the `send` in the same class. Decorators should be completely transparent, so in a decorator the template class should not be used. Also, in a decorator, the underlying adapter should not be exposed.

I propose to have an abstract `HttpAdapterDecorator` in the package. The name is self-describing I think.

**Comment by egeloen** [comment]
Why does the template is a problem for you in a decorator context? I have implemented is this way because the send method is always called by all "templated" methods, so, decorating the send method will automatically decorate all other "templated" methods.

**Comment by sagikazarmark** [comment]
It breaks the decorator pattern by design:

``` php
<?php

class Decorated implements HttpAdapterInterface
{
	public function get($url, ...)
	{
		// I am doing something very important here
	}

	// some other code
}

class Decorator extends AbstractHttpAdapterTemplate
{
	public function __construct(Decorated $decorated)
	{
		$this->decorated = $decorated;
	}

	public function send(...)
	{
		// Decorated::get won't be called ever
	}
}
```

You should be able to decorate any class implementing the interface. The adapter template is a very generic case, which makes sense for implementations, but not for decorations.

**Comment by egeloen** [comment]
@sagikazarmark I'm currently working on moving the event dispatching system in a decorator. The point is I'm a little bit lost in order to fix this issue at the same time... Can you point me a use case where you want to do something on the `get` method that you don't want on the `sendRequest` with a request configured with the `GET` method?

The point is if you do something for a `GET` request you want to do it in the `get` method, the `send` method and  the `sendRequest` method as well not only in the `get` method. Now, knowing the implementation will always use the `sendRequest` as final method (not the case right now but I will update the code to reflect that). Then, isn't it better to always implement your feature in the `sendRequest` method? It will avoid code duplication for all cases (This is what I would do for the event dispatcher).

**Comment by sagikazarmark** [comment]
Honestly, I tend to agree with you and I can't say I have a use case in mind. However it is still true that a decorator must decorate an object in every aspect. So either have a strong notice somewhere that it is not a decorator by the decorator pattern or don't call it a decorator.

**Comment by egeloen** [comment]
To well distinguish the two adapters, I can introduce a `PsrHttpAdapterInterface` which only hold the `sendRequest` and `sendRequests`. It reflects this interface only deals with Psr requests (final methods called in the process) and then, introduce an `AbstractHttpAdapterDecorator` which decorates the `PsrHttpAdapterInterface`. 

Of course, on top of that, the `HttpAdapterInterface` extends the `PsrHttpAdapterInterface` and then, everything is fine.

What do you think?

**Comment by sagikazarmark** [comment]
And what about `get`, `post`, etc methods? Will those be part of the decorator? If yes, how? If no, how will the decorator be useful? You pass a `PsrHttpAdapter` in, which might eventually be an `HttpAdapter`. What about those methods then?

Another thing: if the minimum requirement will be PHP 5.4, you could transform the Template class to a trait, because inheritance doesn't really matter here.

**Comment by egeloen** [comment]
The point is technically, in the event system, I don't see an easy way to recall the `get`, `post`, `trace` or even `send` method because your input has been converted to an internal request in order to be processed by listeners in the pre send event. Only after that, I call the decorated adapter and so, this is why I tend to pass everything by the `sendRequest` and `sendRequests`...

**Comment by sagikazarmark** [comment]
We have two different things to consider here: which way is useful and which can technically be called a decorator. I don't have a problem with having the actual codebase, but it is not a decorator which fits in the term declared by the decorator pattern.

You could simply "forget" the HTTP verb methods for a short time, and implement things without those. IIRC the only part where those are implemented is the template class. When you are done, you can simply add those back with a trait and an interface indicating the existence of those methods. But I guess you plan something similar based on the new `PsrHttpAdapterInterface`. ;)

**Comment by egeloen** [comment]
Closing as #78 is merged and I don't see a way/use case for recall non psr http adapter methods such as `get`, `post`, ...
