### ISSUE TITLE
Http adapter in events

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#81]
Shouldn't the EventDispatcherDecorator populate events with the decorated adapter instead of the decorator?

**Comment by sagikazarmark** [comment]
Also, shouldn't the events be immutable (except some necessary mutability, like stopPropagation)? (I mean the setHttpAdapter method here.

**Comment by egeloen** [comment]
For the first question: I'm :-1: for injecting the decorated adapter. The point is some listeners call itself the http adapter and expects the http adapter to redipatch the events. For example, the retry subscriber will populate a retry count parameter in the request. Then, we send the retry request and in this sending, we want the subscriber to check the params in order to retry it if nececessary (according to the user strategy). So, passing the decorator is the expected/wanted behavior.

For the mutability of the http adapter in the event, I agree the setter should be removed.

**Comment by sagikazarmark** [comment]
Ok, I wasn't aware of this behaviour.
