### ISSUE TITLE
RedirectSubscriber can't work together with another subscribers which listens to Exception event

### ISSUE THREAD

**Issue by im-denisenko** [egeloen/ivory-http-adapter#87]
If RedirectSubscriber configured to throw exception when it reach maximum number of redirects, it will do that. But then, PHP will immediately die with fatal error. 

Problem is here (my case), [at this line](https://github.com/egeloen/ivory-http-adapter/blob/master/src/Event/Subscriber/RetrySubscriber.php#L68), nobody checks if exception actually has a request, but [here](https://github.com/egeloen/ivory-http-adapter/blob/master/src/Event/Retry/Retry.php#L58) we have typehint with exact class name. So, when ```$event->getException()->getRequest()``` returns ```null```, happens fatal error.

Moreover, some other subscribers seems also be affected. [Here](https://github.com/egeloen/ivory-http-adapter/blob/master/src/Event/Subscriber/StopwatchSubscriber.php#L93), [here](https://github.com/egeloen/ivory-http-adapter/blob/master/src/Event/Subscriber/CookieSubscriber.php#L93).

**Comment by sagikazarmark** [comment]
@im-denisenko I am going through the whole event dispatching part, will try to look into this.

**Comment by egeloen** [comment]
IMO, the issue is the request should be populated into the exception by the subscribers and not the adapter which is what is done currently... Then, the exception should always wrap the request. What do you think? 

An other issue I can see is the fact that we can transform an exception into a response by setting it on the exception but then, the next subscriber should take that into account (not the case right now).

**Comment by egeloen** [comment]
For the record, it is broken because at the beginning I throw the exception directly in the subscriber which brokes everything (the next subscribers were not triggered). I have fixed it but then, this part becomes broken...

**Comment by sagikazarmark** [comment]
How could it be done in the subscribers? IMO the request and the optional response should be set in the catch. But I only say this after a first look at the problem which seems to be much more complex.

Another thing popped into my mind: Why are the request and response an attribute of the exception and not the event. IMO that could solve the issue, since the request would be set only once and is not needed to be set over and over again, because of the exception is being overwritten.

**Comment by sagikazarmark** [comment]
Ah, I guess the reason is to be consistent with the MultiException event.

We could change that one to have two object stores for requests and responses indexed by the exception.

**Comment by egeloen** [comment]
I will try to fix it this week.

**Comment by egeloen** [comment]
@im-denisenko Your issue has been fixed in the refernced PR! Can you confirm? :)

**Comment by im-denisenko** [comment]
@egeloen Yep, confirmed. Problem is gone. Thanks!

**Comment by egeloen** [comment]
Thanks for the feedback!
