### ISSUE TITLE
PSR HTTP Adapter decorator questions

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#91]
- Shouldn't it be abstract? Or is the point to create a proxy for PsrHttpAdapterInterfaces? (In this case there could be an abstract version to support creating decorators)
- I don't really get why the `decorate` method is a good solution. IMO it adds unnecessary overhead. Why can't it just call the function (sendRequest/sendRequests) directly?

**Comment by sagikazarmark** [comment]
Also, the `sendInternalRequest` method does not return anything.

**Comment by egeloen** [comment]
> Shouldn't it be abstract? Or is the point to create a proxy for PsrHttpAdapterInterfaces? (In this case there could be an abstract version to support creating decorators)

Currently, my philosophy is to only put a class abstract if there is something abstract to implement. Here, there is nothing to implement in order to make it working so, I have let it not abstract. Futhermore, IMO, there is nothing which prevent you to extend it (abstract ot not), so I don't really get your point here.

> I don't really get why the decorate method is a good solution. IMO it adds unnecessary overhead. Why can't it just call the function (sendRequest/sendRequests) directly?

Let me explain you why I have designed it this way. If you take a look to the `StopwatchHttpAdapter`, I just have to override the decorate method and I don't have to duplicate the code from the `sendInternalRequest`/`sendInternalRequests`. I understand it add overhead but then, it will result to code duplication. So, what is better? :) 

> Also, the sendInternalRequest method does not return anything.

Euh, this method returns something but the `sendInternalRequets` does not return anything by design. Aren't you confusing between `sendRequest` vs `sendInternalRequest`?

**Comment by sagikazarmark** [comment]
> Currently, my philosophy is to only put a class abstract

There is something to implement. You mentioned the `StopwatchHttpAdapter`. So some custom logic is always needed.

> it will result to code duplication.

What about calling `parent::sendInternalRequest[s]`? IMO that is much cleaner.

> Aren't you confusing between sendRequest vs sendInternalRequest?

Meh, probably I do. I am trying to create a generic authenticating plugin (both with a decorator and an event subscriber) which might also replace the current one. (My problem with the current BasicAuth approach is that it is too specific to Basic auth, while there is a general need for further types of authentication, like in case of APIs).

You can take a look at the idea here:

https://github.com/indigophp/http-adapter-auth
